INSERT INTO category (name, image) VALUES ('Category 1', 'category1.png');
INSERT INTO category (name, image) VALUES ('Category 2', 'category2.png');
INSERT INTO category (name, image) VALUES ('Category 3', 'category3.png');
INSERT INTO category (name, image) VALUES ('Category 4', 'category4.png');
INSERT INTO category (name, image) VALUES ('Category 5', 'category5.png');
INSERT INTO category (name, image) VALUES ('Category 6', 'category6.png');
INSERT INTO category (name, image) VALUES ('Category 7', 'category7.png');
INSERT INTO category (name, image) VALUES ('Category 8', 'category8.png');
INSERT INTO category (name, image) VALUES ('Category 9', 'category9.png');
INSERT INTO category (name, image) VALUES ('Category 10', 'category10.png');
INSERT INTO category (name, image) VALUES ('Category 11', 'category11.png');
INSERT INTO category (name, image) VALUES ('Category 12', 'category12.png');
INSERT INTO category (name, image) VALUES ('Category 13', 'category13.png');
INSERT INTO category (name, image) VALUES ('Category 14', 'category14.png');
INSERT INTO category (name, image) VALUES ('Category 15', 'category15.png');
INSERT INTO category (name, image) VALUES ('Category 16', 'category16.png');
INSERT INTO category (name, image) VALUES ('Category 17', 'category17.png');
INSERT INTO category (name, image) VALUES ('Category 18', 'category18.png');
INSERT INTO category (name, image) VALUES ('Category 19', 'category19.png');
INSERT INTO category (name, image) VALUES ('Category 20', 'category20.png');
INSERT INTO category (name, image) VALUES ('Category 21', 'category21.png');
INSERT INTO category (name, image) VALUES ('Category 22', 'category22.png');
INSERT INTO category (name, image) VALUES ('Category 23', 'category23.png');
INSERT INTO category (name, image) VALUES ('Category 24', 'category24.png');
INSERT INTO category (name, image) VALUES ('Category 25', 'category25.png');
INSERT INTO category (name, image) VALUES ('Category 26', 'category26.png');
INSERT INTO category (name, image) VALUES ('Category 27', 'category27.png');
INSERT INTO category (name, image) VALUES ('Category 28', 'category28.png');
INSERT INTO category (name, image) VALUES ('Category 29', 'category29.png');
INSERT INTO category (name, image) VALUES ('Category 30', 'category30.png');
INSERT INTO category (name, image) VALUES ('Category 31', 'category31.png');
INSERT INTO category (name, image) VALUES ('Category 32', 'category32.png');
INSERT INTO category (name, image) VALUES ('Category 33', 'category33.png');
INSERT INTO category (name, image) VALUES ('Category 34', 'category34.png');
INSERT INTO category (name, image) VALUES ('Category 35', 'category35.png');
INSERT INTO category (name, image) VALUES ('Category 36', 'category36.png');
INSERT INTO category (name, image) VALUES ('Category 37', 'category37.png');
INSERT INTO category (name, image) VALUES ('Category 38', 'category38.png');
INSERT INTO category (name, image) VALUES ('Category 39', 'category39.png');
INSERT INTO category (name, image) VALUES ('Category 40', 'category40.png');
INSERT INTO category (name, image) VALUES ('Category 41', 'category41.png');
INSERT INTO category (name, image) VALUES ('Category 42', 'category42.png');
INSERT INTO category (name, image) VALUES ('Category 43', 'category43.png');
INSERT INTO category (name, image) VALUES ('Category 44', 'category44.png');
INSERT INTO category (name, image) VALUES ('Category 45', 'category45.png');
INSERT INTO category (name, image) VALUES ('Category 46', 'category46.png');
INSERT INTO category (name, image) VALUES ('Category 47', 'category47.png');
INSERT INTO category (name, image) VALUES ('Category 48', 'category48.png');
INSERT INTO category (name, image) VALUES ('Category 49', 'category49.png');
INSERT INTO category (name, image) VALUES ('Category 50', 'category50.png');
INSERT INTO category (name, image) VALUES ('Category 51', 'category51.png');
INSERT INTO category (name, image) VALUES ('Category 52', 'category52.png');
INSERT INTO category (name, image) VALUES ('Category 53', 'category53.png');
INSERT INTO category (name, image) VALUES ('Category 54', 'category54.png');
INSERT INTO category (name, image) VALUES ('Category 55', 'category55.png');
INSERT INTO category (name, image) VALUES ('Category 56', 'category56.png');
INSERT INTO category (name, image) VALUES ('Category 57', 'category57.png');
INSERT INTO category (name, image) VALUES ('Category 58', 'category58.png');
INSERT INTO category (name, image) VALUES ('Category 59', 'category59.png');
INSERT INTO category (name, image) VALUES ('Category 60', 'category60.png');
INSERT INTO category (name, image) VALUES ('Category 61', 'category61.png');
INSERT INTO category (name, image) VALUES ('Category 62', 'category62.png');
INSERT INTO category (name, image) VALUES ('Category 63', 'category63.png');
INSERT INTO category (name, image) VALUES ('Category 64', 'category64.png');
INSERT INTO category (name, image) VALUES ('Category 65', 'category65.png');
INSERT INTO category (name, image) VALUES ('Category 66', 'category66.png');
INSERT INTO category (name, image) VALUES ('Category 67', 'category67.png');
INSERT INTO category (name, image) VALUES ('Category 68', 'category68.png');
INSERT INTO category (name, image) VALUES ('Category 69', 'category69.png');
INSERT INTO category (name, image) VALUES ('Category 70', 'category70.png');
INSERT INTO category (name, image) VALUES ('Category 71', 'category71.png');
INSERT INTO category (name, image) VALUES ('Category 72', 'category72.png');
INSERT INTO category (name, image) VALUES ('Category 73', 'category73.png');
INSERT INTO category (name, image) VALUES ('Category 74', 'category74.png');
INSERT INTO category (name, image) VALUES ('Category 75', 'category75.png');
INSERT INTO category (name, image) VALUES ('Category 76', 'category76.png');
INSERT INTO category (name, image) VALUES ('Category 77', 'category77.png');
INSERT INTO category (name, image) VALUES ('Category 78', 'category78.png');
INSERT INTO category (name, image) VALUES ('Category 79', 'category79.png');
INSERT INTO category (name, image) VALUES ('Category 80', 'category80.png');
INSERT INTO category (name, image) VALUES ('Category 81', 'category81.png');
INSERT INTO category (name, image) VALUES ('Category 82', 'category82.png');
INSERT INTO category (name, image) VALUES ('Category 83', 'category83.png');
INSERT INTO category (name, image) VALUES ('Category 84', 'category84.png');
INSERT INTO category (name, image) VALUES ('Category 85', 'category85.png');
INSERT INTO category (name, image) VALUES ('Category 86', 'category86.png');
INSERT INTO category (name, image) VALUES ('Category 87', 'category87.png');
INSERT INTO category (name, image) VALUES ('Category 88', 'category88.png');
INSERT INTO category (name, image) VALUES ('Category 89', 'category89.png');
INSERT INTO category (name, image) VALUES ('Category 90', 'category90.png');
INSERT INTO category (name, image) VALUES ('Category 91', 'category91.png');
INSERT INTO category (name, image) VALUES ('Category 92', 'category92.png');
INSERT INTO category (name, image) VALUES ('Category 93', 'category93.png');
INSERT INTO category (name, image) VALUES ('Category 94', 'category94.png');
INSERT INTO category (name, image) VALUES ('Category 95', 'category95.png');
INSERT INTO category (name, image) VALUES ('Category 96', 'category96.png');
INSERT INTO category (name, image) VALUES ('Category 97', 'category97.png');
INSERT INTO category (name, image) VALUES ('Category 98', 'category98.png');
INSERT INTO category (name, image) VALUES ('Category 99', 'category99.png');
INSERT INTO category (name, image) VALUES ('Category 100', 'category100.png');
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user1', 'user1@gmail.com', '$2a$10$y3CwKGgA3Ucd3uQyMilFC.mbPjhmYNBeNKD7Xwvzm5ELMESFfE8DC', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user2', 'user2@gmail.com', '$2a$10$HyK0CgNmSrodKWzQZ3piu.jeYUy4fVsvJbzAwNIPIUaRGQmATk.hK', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user3', 'user3@gmail.com', '$2a$10$ey6F4erZBrxKdR7boKWPfePFl08bzyiPrS2hFFfAe9LlLLtkOAJ0i', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user4', 'user4@gmail.com', '$2a$10$x4EGw2b/7HwAWuMHWGhxK.h/i9oWTF.l4MyUYRyqJ4blOCnEOPEzq', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user5', 'user5@gmail.com', '$2a$10$22397iQrkTtmjDZrUQBBMe1sKgDWv4xjjF3Bhfs/qCfteYjLj48p.', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user6', 'user6@gmail.com', '$2a$10$YN2rVm4bK2FNHgBIK9.LO.Wa8Ch9Rh7.Ki0ps57nwpNUGo5QSWt6G', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user7', 'user7@gmail.com', '$2a$10$5rEnLUcHGByYCDgYsMgqQefaJnCQ6o/k5cOsAfBEYM.fpKFETi3ke', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user8', 'user8@gmail.com', '$2a$10$OAKBJSaQHwOWDTLcMRlBJO0gpX6mGs3YgAhZ.rAii89XRfWPq.Kme', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user9', 'user9@gmail.com', '$2a$10$65vAAQn6bVtvhX8ufPn9BuHU/ILiY7RBOvkALwU7c.mruwqCfiynC', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user10', 'user10@gmail.com', '$2a$10$SSKmNpPgE62IISdyO.kRr..5GK.edqoaCp8UlJGJETZ76usKnTfIm', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user11', 'user11@gmail.com', '$2a$10$4pLbg8cFjXK8eDSFhKHtCOPY3ucN/dAjz8xBhlZ2cyW45EnP0kiT.', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user12', 'user12@gmail.com', '$2a$10$Tg6hAGZIxyvR/IOk8dpUxuC8HHKtVtcMFETxgGftNRtAMoJ3ife76', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user13', 'user13@gmail.com', '$2a$10$TMCNOZ1WiyJ3InOrvoVV8etBD0A97JviC85TiIcB2J1Vt8J.GeOvu', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user14', 'user14@gmail.com', '$2a$10$SXc46rsNN1TCMv31sNtxL.apzGbJTASEfJBKi1/6CwYVB2kiccfeq', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user15', 'user15@gmail.com', '$2a$10$GDBH3bYpeOC82KEkeCLHKuMbg.trfjrhrcQt6F0fc4nqpUEvlODaO', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user16', 'user16@gmail.com', '$2a$10$128xH7WH9QJNOgn7y.fWhep7Y8bXhHlfIE68.EtADF6PGmP1F14ve', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user17', 'user17@gmail.com', '$2a$10$MX8vwY8sM7mGHoDUMcJPkuDQyBOLP.ie7gJPuGbTvydTEFpgCpdNi', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user18', 'user18@gmail.com', '$2a$10$b5t6t2jXfoCbLC3rurkST.UdWL7DVTxhMVOXYQaXQZ7prp8vbE.d6', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user19', 'user19@gmail.com', '$2a$10$2Un6S1xC7fMyO2e2FzLgde3bBxHUToCkBWOC2SGya9P.TCL1SXw82', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user20', 'user20@gmail.com', '$2a$10$4lF7lX6.vYeIUm2L5GviEOPfcRheSs7Ma4Ji6SgUkiwDXWK3T6IZO', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user21', 'user21@gmail.com', '$2a$10$CEsGmopSaRcKhX42ewLjBOo/w5Bx..HaCrEZu6Zpl1CWhuufwlfTy', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user22', 'user22@gmail.com', '$2a$10$K0cgOtjDgHSsNc8MEJWwSesxw1luiEqI7L3Sbg3Ix.J8fHL7a7cW2', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user23', 'user23@gmail.com', '$2a$10$NITPkXeNFv2GCrUhYSUiwOxEJufyb5NNtdJFDIJcXx5SjjtW8cXQu', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user24', 'user24@gmail.com', '$2a$10$63hKrQNDHELR1kDqDIXLhOxGrMi1bTTL3HsvfMpMMl9fiAZH42OJG', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user25', 'user25@gmail.com', '$2a$10$/p0v2tibX85UVRTrhUqqLOFrtfIBcqYZQSJvmp/E1ROoVE0i3z.7S', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user26', 'user26@gmail.com', '$2a$10$YfNXjatnosbuCg01631V5uyWEuJJHmdEqjXNrb.nPjpSmp01gC1wm', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user27', 'user27@gmail.com', '$2a$10$yCNcTa/gYsbe7Og/cYWtT.QW8MjGlh1QJYazKAFXITEkTQjx5Kdz.', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user28', 'user28@gmail.com', '$2a$10$WpVtI.UCNUtWBdDektChEu1gp76v5SfkoD5Upd/1yRrEXYnMzH.PG', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user29', 'user29@gmail.com', '$2a$10$4ncKPp64MBWLDOODdIFDqupjH8ARKGU1twqBbo6M7IJUxgX5eKqGK', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user30', 'user30@gmail.com', '$2a$10$ExDUGGeruSzjv0KPzLO/3etvPBW1SA8Yl9mQXHJQ9skXVAjmPVjo6', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user31', 'user31@gmail.com', '$2a$10$I1a.N9bU3OJaNeLmcxsoMe44hajsutKU0edMC.atCwLPgyidXqotK', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user32', 'user32@gmail.com', '$2a$10$BlxX5fWInd0ZPQfq.hcDK.RCuEYn4hjIzz1b1kCamu8/J4gcpG.mK', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user33', 'user33@gmail.com', '$2a$10$hpd5tC/s8/ERscDMm1hrY.puw7f1h5zrtAl6RySoIhghsydqM8yD6', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user34', 'user34@gmail.com', '$2a$10$jTfOW0RebQF7I/IjtLldb.qnFaDkgkxBF/otEQSv3S4yiM8zH0sQ2', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user35', 'user35@gmail.com', '$2a$10$oX1QioRdCADjGyVJF3UnSeqLsttnyP/oxRen9iDtb8kk5eogl12iK', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user36', 'user36@gmail.com', '$2a$10$4m1s0qw2pN1hZ3bHA1dgBuJOVUOKhftM47cMC.UiD9GCK.jjR4AZW', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user37', 'user37@gmail.com', '$2a$10$Eph8pLwdWnl8d9uKgljxCuz2H6vpIoEOJimj5zNjXZkIeedej3k/a', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user38', 'user38@gmail.com', '$2a$10$JiNZYX0boSIFgJsbvWEucOJFn3qHUqA8vrH2N8t8qZtAgeJHLK8QC', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user39', 'user39@gmail.com', '$2a$10$UEXhwRa3ps5QA.2Md0Q8/OV.SlZEB68tmYbMDTDuzJkP6FiaitBda', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user40', 'user40@gmail.com', '$2a$10$ztPMhd0pfmpt8Bt7iwgZB.FQpx4bgf.AxydnGc9rwr4.Qzf0/ihSG', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user41', 'user41@gmail.com', '$2a$10$K1vFd9VpYOXciYdesSlsBu8jTj6e2yutw/mRJndIEpv3WW4lJDc2.', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user42', 'user42@gmail.com', '$2a$10$n.TyrRG75yOLL9iJG.gUf.ymZywY825RY80RFd53BexjvRs5dOWtq', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user43', 'user43@gmail.com', '$2a$10$eVLCIGZQUoq84T8AZtIwyeGPpxr6lIjvaFRuKHmmU3GbNHmY6Om.a', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user44', 'user44@gmail.com', '$2a$10$kLEM18GT0qS0EULjEbxTQehADM7GNVoT5HC605vGhlnZa1DYtq0cq', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user45', 'user45@gmail.com', '$2a$10$seWZIBN3tiLzV1CYnelqF.y6WUoNMR4sPn8GaDDNxlnjROHSipP4O', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user46', 'user46@gmail.com', '$2a$10$kuhHgHuzPuuGgpxAziWSDu/ACDULjEBWZjlD8BHR7ltDe6apLBk8i', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user47', 'user47@gmail.com', '$2a$10$LTL/q6PvISHj43IXgknDm.mMOti/.NUsALaNS4Q.DrXfV4JgTDvme', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user48', 'user48@gmail.com', '$2a$10$Gta9ve32Z7DdEnN6tp7QFuRsJ6hJ2ef4WqQxNmEzGqglvHUQRFf1i', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user49', 'user49@gmail.com', '$2a$10$a8u9HRKb/0CiUXbEhijYFuu4k.Tkykim/Zbm3kHKR.zdFJq8Hs0oy', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user50', 'user50@gmail.com', '$2a$10$UZqFr1jBEPuPTpKXCJ9nte8T0m2jsyyWu7CaL0v01f5ZeaybEV6kO', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user51', 'user51@gmail.com', '$2a$10$aUvQrfMKXfZoi.5SbUI13OmBCicmd9IadQu95xr4.o6IlOu491Rvy', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user52', 'user52@gmail.com', '$2a$10$XU7jnPuhFQWZ0w0e1AOLFOusClTtLzggnQsbvme4oin223hoL32r6', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user53', 'user53@gmail.com', '$2a$10$cvl5DrYjlPAEvsL.FuVXh.07MBDX83n9Qfw0Fi6whx2YjnriYDsGK', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user54', 'user54@gmail.com', '$2a$10$J4CGCGHn1u.vGkaJcDlLt.iOZJtBSgidkjAAuZRe0FA/V/dTjsPAa', 'USER_PREMIUM', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user55', 'user55@gmail.com', '$2a$10$F6XMV3z8eQAHkoqe0ZQqCuGDi0ElTLeFw7.lXGYDAO86AJ4mvUECS', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user56', 'user56@gmail.com', '$2a$10$y7G6WF1x87Eo.lKbycLuqOeGsJl7ZdOvCDJqoua6x32/pN1f1VvvW', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user57', 'user57@gmail.com', '$2a$10$RRktfvwtAT3.e75mTxKnvOgVJe0V4tzDWmWjJGRykFvvs2UYBm7By', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user58', 'user58@gmail.com', '$2a$10$EP7SVu6Gj0NMG2pxoxfMKOvWfgcTHrzeuK6Wh1/8uTi8Fa.HmsMGC', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user59', 'user59@gmail.com', '$2a$10$WzrvM4sfV.nQ9LaLE8PDauRu8GkYI7fjEmk55qmZi9IojAyaF0UJe', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user60', 'user60@gmail.com', '$2a$10$/wm1loJdmnsjVufzPPMYCuUFBv4.1mS03Uz4KuEnoMtASp3fVJN5u', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user61', 'user61@gmail.com', '$2a$10$NRqy8i4yrq/ah1voQwzbG.w78ExHx2SFCrQjjG1RJdDZnrZ6zukje', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user62', 'user62@gmail.com', '$2a$10$ENW3MVtb/N.VykRZ.x6W4.vsGbNo68BKl/0fmw2lnDXjo941afXQe', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user63', 'user63@gmail.com', '$2a$10$WZKMINkXePlfNyloWyYC3uYS16tqZDVBn4WaGCcrO1JEQEzebsUMa', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user64', 'user64@gmail.com', '$2a$10$ZxK4agwIqTUyCKUuaDxzE.ab1YE7JsCPSNtl9C1rgnsXrvxaEyH1m', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user65', 'user65@gmail.com', '$2a$10$qAa6BCZF.wV2ZGxYoJRbwuL6KIPKwefLwPM7mHdcC7GdlY8lYzf2m', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user66', 'user66@gmail.com', '$2a$10$EicsaiBCSfBwnQ5ZxmzmnehAuyW/ooSMiSgBL8jS/kAOZgM1bOxiG', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user67', 'user67@gmail.com', '$2a$10$ytqqVlmZ8KpqlMdpemuEJuvwBfcXE7MRwlGT/VToJsnGV7OHxgQoW', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user68', 'user68@gmail.com', '$2a$10$Uz4iPSQqIKDY/DcQmEBB7.pI9ziHDiZlRoi/Zg/TIwlKVV0wBRP32', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user69', 'user69@gmail.com', '$2a$10$LWMFGi1f.U3LGU8s9jg4RuyY8coLPghK/O1uA9rk1ctbFBqDfsbxW', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user70', 'user70@gmail.com', '$2a$10$RKNynA.OZJcjHH6NsLVA3.Rrfjwo9qP7tsGrgf81PRLErGg60I7ce', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user71', 'user71@gmail.com', '$2a$10$yANBkfhrGn2fQwU6dXvGg.3FjMs7tJpwQ5p3gSJo65W2pROFdKKmK', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user72', 'user72@gmail.com', '$2a$10$PNTO/Zd3QQrLlf1i250ilOZ2oMboHbPtDtQVEJTvHAsymZqziwZJ2', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user73', 'user73@gmail.com', '$2a$10$xCRgBDmVGWIqpqawYqQZ0OfTWFJgzZ6tl3bQJKI/yalez77GkqmSy', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user74', 'user74@gmail.com', '$2a$10$NNvu6ZUaFIPU5l8ujGKCguTaLPwPqnGcE0omPXQy/FDN4mUguKf9e', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user75', 'user75@gmail.com', '$2a$10$ruINsAfr.x50CMcxX3esLOASg77C4rQ.Teb0KINqWLWXVo9sZln.i', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user76', 'user76@gmail.com', '$2a$10$aYOa/DbzkN37cE6IjztWtukJ1OhQ5mTKuQ4LH6LrLTBJDotXMmC4K', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user77', 'user77@gmail.com', '$2a$10$1AbQaczRcgx.u73WAQoJyeY4s7fY/SPH2GgGx4SmqLhAjSlVWu0z6', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user78', 'user78@gmail.com', '$2a$10$QQKG7nOHHWxrQn1ivpOVqO2k4TUCbxrw3BuDrORh8NQGg9eSVdNSm', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user79', 'user79@gmail.com', '$2a$10$/iVIeR/rH1e5FuEFth2sgu31ja55NKAkItuziF/Fkhm9iTpisanre', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user80', 'user80@gmail.com', '$2a$10$ny024CVCdIh3t9giGUa5OeotKOHJiop245IYLtuK0cv2Od.55F5Wy', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user81', 'user81@gmail.com', '$2a$10$Ot0HUZd1.6xG/Xw2WeRjGux23extIrKY75u6I9lM1EQPcTHNqTLYm', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user82', 'user82@gmail.com', '$2a$10$R8x0jcGNzRTpqCZ4HUlQ9.7mzeaGG1BkGJG.4IOazh1PSHbaxsIO2', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user83', 'user83@gmail.com', '$2a$10$4vjnhgH7Rtz2LnrZCzsEyeSZvYo/QQd7KAX/78lDQYWIKC/2pvKla', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user84', 'user84@gmail.com', '$2a$10$/6tJ4oFNKRclv3d/Z4wTqegqDVQwcf841UI7P8uUTRLLyhu0/oX5q', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user85', 'user85@gmail.com', '$2a$10$Gk84LMqhs0vYLUhNMT5QLeQ7845aKavI8Y1RJuH4PoSOb8tlpGW/.', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user86', 'user86@gmail.com', '$2a$10$s5zSOLzwx.wRxlZLcPfqqegf0Gg/9NwATxd1vYCrDDjxxGARAgEly', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user87', 'user87@gmail.com', '$2a$10$9gBABbT.ixurilNBPYoHbut/FrskJGt.Gq2Pv3DML43wsuq0p.fDu', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user88', 'user88@gmail.com', '$2a$10$kQGqUqlh/PCUZak0B0TQa.QD6cs1As3hFNCcSU2BP3vmkRW5svFd2', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user89', 'user89@gmail.com', '$2a$10$QxgCdGCP3m2evhNQcK9Vk.h4bWL4Irqlo70G7NgbAYi.moMdeD0qG', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user90', 'user90@gmail.com', '$2a$10$62rpA/13BMERd/DM38v1D.jX/dkeK0BooPve3Toq3WwGdDRqsHznW', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user91', 'user91@gmail.com', '$2a$10$hILzGc3N.nBiyPDSSmzwMujaNrv2txOYvyvqU1Sj3irfhoN4Bjy/C', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user92', 'user92@gmail.com', '$2a$10$aTiuiEzaI8A.K8jkQd2h6u3Y6aKltRHXhmtbqiabBSS.mInCjjVoi', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user93', 'user93@gmail.com', '$2a$10$6Ah0kic7AzvIdEklLoCzaux8txxEfzTDp.AAXJEL5xqUI1Icx4wPG', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user94', 'user94@gmail.com', '$2a$10$yTt5bTbPHJlJvY96wNG.UevylefMleS0g0TRc8FNjVbrLhb0q7gL2', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user95', 'user95@gmail.com', '$2a$10$tC4wIHYUqJK9NALOdgYxJOb.iFgt6W/0/YNlRS2R3wVpspdWSTmS2', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user96', 'user96@gmail.com', '$2a$10$UyHnHVlOY3uDbxhc6S02GuxOGrbmyvqZ74MySN3GYn7p8cyaEJvp6', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user97', 'user97@gmail.com', '$2a$10$.bcJX5YN4bU4sFEo7SZfVOavFDrY8hZT2xMT47SN3ralv8bH.RoZi', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user98', 'user98@gmail.com', '$2a$10$hYhY9evKkQrdnM0.rcJWyuOJ/sebg9BuGQh4Rg7LgMzdKyTmO6y.y', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user99', 'user99@gmail.com', '$2a$10$4O5yJZisLoj3JuLtsS3Bnerr8GOkdx.Y4iRLrK0XwNu6JTN2F5RfG', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user100', 'user100@gmail.com', '$2a$10$LIMwsh7xDQM1MncN3BfuaeYKVb1g3xbATNu90vgXs953lbJck.gl6', 'USER', true, true, true, true);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 56, 'Listing 1', 'Description for listing 1', 'image1.png', 619.79, false, '2024-06-20T14:49:05.427204975', 23);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 46, 'Listing 2', 'Description for listing 2', 'image2.png', 650.08, false, '2024-06-20T14:49:05.428627996', 30);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 81, 'Listing 3', 'Description for listing 3', 'image3.png', 549.19, false, '2024-06-20T14:49:05.428718716', 96);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 73, 'Listing 4', 'Description for listing 4', 'image4.png', 43.89, false, '2024-06-20T14:49:05.428795609', 28);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 12, 'Listing 5', 'Description for listing 5', 'image5.png', 37.20, false, '2024-06-20T14:49:05.428868006', 63);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 68, 'Listing 6', 'Description for listing 6', 'image6.png', 556.09, false, '2024-06-20T14:49:05.428920599', 28);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 96, 'Listing 7', 'Description for listing 7', 'image7.png', 480.34, false, '2024-06-20T14:49:05.428972950', 60);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 96, 'Listing 8', 'Description for listing 8', 'image8.png', 943.89, false, '2024-06-20T14:49:05.429030173', 42);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 24, 'Listing 9', 'Description for listing 9', 'image9.png', 449.67, false, '2024-06-20T14:49:05.429103209', 47);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 44, 'Listing 10', 'Description for listing 10', 'image10.png', 864.21, false, '2024-06-20T14:49:05.429156689', 100);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 93, 'Listing 11', 'Description for listing 11', 'image11.png', 787.77, false, '2024-06-20T14:49:05.429211281', 81);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 82, 'Listing 12', 'Description for listing 12', 'image12.png', 946.76, false, '2024-06-20T14:49:05.429268422', 71);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 5, 'Listing 13', 'Description for listing 13', 'image13.png', 486.95, false, '2024-06-20T14:49:05.429327044', 81);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 53, 'Listing 14', 'Description for listing 14', 'image14.png', 507.76, false, '2024-06-20T14:49:05.429380779', 37);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 42, 'Listing 15', 'Description for listing 15', 'image15.png', 159.70, false, '2024-06-20T14:49:05.429460007', 82);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 99, 'Listing 16', 'Description for listing 16', 'image16.png', 809.68, false, '2024-06-20T14:49:05.429518251', 21);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 69, 'Listing 17', 'Description for listing 17', 'image17.png', 483.62, false, '2024-06-20T14:49:05.429570956', 85);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 72, 'Listing 18', 'Description for listing 18', 'image18.png', 234.06, false, '2024-06-20T14:49:05.429623609', 28);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 15, 'Listing 19', 'Description for listing 19', 'image19.png', 605.93, false, '2024-06-20T14:49:05.429680992', 77);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 17, 'Listing 20', 'Description for listing 20', 'image20.png', 728.00, false, '2024-06-20T14:49:05.429735021', 52);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 91, 'Listing 21', 'Description for listing 21', 'image21.png', 125.99, false, '2024-06-20T14:49:05.429791744', 61);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 62, 'Listing 22', 'Description for listing 22', 'image22.png', 408.96, false, '2024-06-20T14:49:05.429852785', 49);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 5, 'Listing 23', 'Description for listing 23', 'image23.png', 939.86, false, '2024-06-20T14:49:05.429918363', 10);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 36, 'Listing 24', 'Description for listing 24', 'image24.png', 268.40, false, '2024-06-20T14:49:05.429972296', 21);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 88, 'Listing 25', 'Description for listing 25', 'image25.png', 926.59, false, '2024-06-20T14:49:05.430042800', 63);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 51, 'Listing 26', 'Description for listing 26', 'image26.png', 501.64, false, '2024-06-20T14:49:05.430114064', 85);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 68, 'Listing 27', 'Description for listing 27', 'image27.png', 184.01, false, '2024-06-20T14:49:05.430169345', 14);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 100, 'Listing 28', 'Description for listing 28', 'image28.png', 109.39, false, '2024-06-20T14:49:05.430220390', 32);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 60, 'Listing 29', 'Description for listing 29', 'image29.png', 280.31, false, '2024-06-20T14:49:05.430272327', 61);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 71, 'Listing 30', 'Description for listing 30', 'image30.png', 66.07, false, '2024-06-20T14:49:05.430328518', 12);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 32, 'Listing 31', 'Description for listing 31', 'image31.png', 777.74, false, '2024-06-20T14:49:05.430381856', 39);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 97, 'Listing 32', 'Description for listing 32', 'image32.png', 530.33, false, '2024-06-20T14:49:05.430433538', 22);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 12, 'Listing 33', 'Description for listing 33', 'image33.png', 106.10, false, '2024-06-20T14:49:05.430494072', 71);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 39, 'Listing 34', 'Description for listing 34', 'image34.png', 285.51, false, '2024-06-20T14:49:05.430573083', 56);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 39, 'Listing 35', 'Description for listing 35', 'image35.png', 716.31, false, '2024-06-20T14:49:05.430624525', 2);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 69, 'Listing 36', 'Description for listing 36', 'image36.png', 840.52, false, '2024-06-20T14:49:05.430678057', 10);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 24, 'Listing 37', 'Description for listing 37', 'image37.png', 327.96, false, '2024-06-20T14:49:05.430732511', 95);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 60, 'Listing 38', 'Description for listing 38', 'image38.png', 396.46, false, '2024-06-20T14:49:05.430790149', 23);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 60, 'Listing 39', 'Description for listing 39', 'image39.png', 999.93, false, '2024-06-20T14:49:05.430844251', 31);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 60, 'Listing 40', 'Description for listing 40', 'image40.png', 189.60, false, '2024-06-20T14:49:05.430898539', 6);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 21, 'Listing 41', 'Description for listing 41', 'image41.png', 699.38, false, '2024-06-20T14:49:05.430954870', 74);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 89, 'Listing 42', 'Description for listing 42', 'image42.png', 558.46, false, '2024-06-20T14:49:05.431007151', 84);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 85, 'Listing 43', 'Description for listing 43', 'image43.png', 21.96, false, '2024-06-20T14:49:05.431175871', 34);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 70, 'Listing 44', 'Description for listing 44', 'image44.png', 450.85, false, '2024-06-20T14:49:05.431241564', 78);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 20, 'Listing 45', 'Description for listing 45', 'image45.png', 724.94, false, '2024-06-20T14:49:05.431324623', 9);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 53, 'Listing 46', 'Description for listing 46', 'image46.png', 986.16, false, '2024-06-20T14:49:05.431370956', 45);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 57, 'Listing 47', 'Description for listing 47', 'image47.png', 774.92, false, '2024-06-20T14:49:05.431416618', 33);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 8, 'Listing 48', 'Description for listing 48', 'image48.png', 118.70, false, '2024-06-20T14:49:05.431514016', 8);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 41, 'Listing 49', 'Description for listing 49', 'image49.png', 683.06, false, '2024-06-20T14:49:05.431560166', 25);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 42, 'Listing 50', 'Description for listing 50', 'image50.png', 410.13, false, '2024-06-20T14:49:05.431603960', 65);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 77, 'Listing 51', 'Description for listing 51', 'image51.png', 3.44, false, '2024-06-20T14:49:05.431647622', 26);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 49, 'Listing 52', 'Description for listing 52', 'image52.png', 411.81, false, '2024-06-20T14:49:05.431716514', 1);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 88, 'Listing 53', 'Description for listing 53', 'image53.png', 3.80, false, '2024-06-20T14:49:05.431759068', 36);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 94, 'Listing 54', 'Description for listing 54', 'image54.png', 182.62, false, '2024-06-20T14:49:05.431842464', 15);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 50, 'Listing 55', 'Description for listing 55', 'image55.png', 682.93, false, '2024-06-20T14:49:05.431915386', 100);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 92, 'Listing 56', 'Description for listing 56', 'image56.png', 23.24, false, '2024-06-20T14:49:05.431963580', 5);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 13, 'Listing 57', 'Description for listing 57', 'image57.png', 505.58, false, '2024-06-20T14:49:05.432064286', 34);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 8, 'Listing 58', 'Description for listing 58', 'image58.png', 594.95, false, '2024-06-20T14:49:05.432125196', 64);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 28, 'Listing 59', 'Description for listing 59', 'image59.png', 452.81, false, '2024-06-20T14:49:05.432172709', 6);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 24, 'Listing 60', 'Description for listing 60', 'image60.png', 209.08, false, '2024-06-20T14:49:05.432218026', 90);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 71, 'Listing 61', 'Description for listing 61', 'image61.png', 244.83, false, '2024-06-20T14:49:05.432260774', 68);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 87, 'Listing 62', 'Description for listing 62', 'image62.png', 222.69, false, '2024-06-20T14:49:05.432308339', 84);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 35, 'Listing 63', 'Description for listing 63', 'image63.png', 883.45, false, '2024-06-20T14:49:05.432354435', 17);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 42, 'Listing 64', 'Description for listing 64', 'image64.png', 156.81, false, '2024-06-20T14:49:05.432400148', 11);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 76, 'Listing 65', 'Description for listing 65', 'image65.png', 982.27, false, '2024-06-20T14:49:05.432482638', 26);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 97, 'Listing 66', 'Description for listing 66', 'image66.png', 365.19, false, '2024-06-20T14:49:05.432532596', 8);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 73, 'Listing 67', 'Description for listing 67', 'image67.png', 705.47, false, '2024-06-20T14:49:05.432581685', 14);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 30, 'Listing 68', 'Description for listing 68', 'image68.png', 825.09, false, '2024-06-20T14:49:05.432624735', 14);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 93, 'Listing 69', 'Description for listing 69', 'image69.png', 519.98, false, '2024-06-20T14:49:05.432669994', 1);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 20, 'Listing 70', 'Description for listing 70', 'image70.png', 895.77, false, '2024-06-20T14:49:05.432731856', 16);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 65, 'Listing 71', 'Description for listing 71', 'image71.png', 380.41, false, '2024-06-20T14:49:05.432787221', 1);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 80, 'Listing 72', 'Description for listing 72', 'image72.png', 696.01, false, '2024-06-20T14:49:05.432831429', 18);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 52, 'Listing 73', 'Description for listing 73', 'image73.png', 412.98, false, '2024-06-20T14:49:05.432890049', 32);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 27, 'Listing 74', 'Description for listing 74', 'image74.png', 89.09, false, '2024-06-20T14:49:05.432935285', 14);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 89, 'Listing 75', 'Description for listing 75', 'image75.png', 641.73, false, '2024-06-20T14:49:05.432976542', 69);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 22, 'Listing 76', 'Description for listing 76', 'image76.png', 131.59, false, '2024-06-20T14:49:05.433017970', 36);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 55, 'Listing 77', 'Description for listing 77', 'image77.png', 809.33, false, '2024-06-20T14:49:05.433063323', 75);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 65, 'Listing 78', 'Description for listing 78', 'image78.png', 242.00, false, '2024-06-20T14:49:05.433106101', 56);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 68, 'Listing 79', 'Description for listing 79', 'image79.png', 884.95, false, '2024-06-20T14:49:05.433158815', 30);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 92, 'Listing 80', 'Description for listing 80', 'image80.png', 275.63, false, '2024-06-20T14:49:05.433204435', 84);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 97, 'Listing 81', 'Description for listing 81', 'image81.png', 422.53, false, '2024-06-20T14:49:05.433244998', 14);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 36, 'Listing 82', 'Description for listing 82', 'image82.png', 154.29, false, '2024-06-20T14:49:05.433290547', 41);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 3, 'Listing 83', 'Description for listing 83', 'image83.png', 535.90, false, '2024-06-20T14:49:05.433331298', 57);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 74, 'Listing 84', 'Description for listing 84', 'image84.png', 692.45, false, '2024-06-20T14:49:05.433375810', 93);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 61, 'Listing 85', 'Description for listing 85', 'image85.png', 890.35, false, '2024-06-20T14:49:05.433416758', 17);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 46, 'Listing 86', 'Description for listing 86', 'image86.png', 785.80, false, '2024-06-20T14:49:05.433462512', 63);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 43, 'Listing 87', 'Description for listing 87', 'image87.png', 775.95, false, '2024-06-20T14:49:05.433504756', 53);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 69, 'Listing 88', 'Description for listing 88', 'image88.png', 184.00, false, '2024-06-20T14:49:05.433558270', 16);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 76, 'Listing 89', 'Description for listing 89', 'image89.png', 23.68, false, '2024-06-20T14:49:05.433602450', 43);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 59, 'Listing 90', 'Description for listing 90', 'image90.png', 656.28, false, '2024-06-20T14:49:05.433646482', 74);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 48, 'Listing 91', 'Description for listing 91', 'image91.png', 253.16, false, '2024-06-20T14:49:05.433693498', 88);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 61, 'Listing 92', 'Description for listing 92', 'image92.png', 476.54, false, '2024-06-20T14:49:05.433734461', 60);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 6, 'Listing 93', 'Description for listing 93', 'image93.png', 699.69, false, '2024-06-20T14:49:05.433778924', 73);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 7, 'Listing 94', 'Description for listing 94', 'image94.png', 804.35, false, '2024-06-20T14:49:05.433834513', 14);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 43, 'Listing 95', 'Description for listing 95', 'image95.png', 658.18, false, '2024-06-20T14:49:05.433880207', 94);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 43, 'Listing 96', 'Description for listing 96', 'image96.png', 718.50, false, '2024-06-20T14:49:05.433921161', 59);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 60, 'Listing 97', 'Description for listing 97', 'image97.png', 402.80, false, '2024-06-20T14:49:05.433986796', 51);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 27, 'Listing 98', 'Description for listing 98', 'image98.png', 372.07, false, '2024-06-20T14:49:05.434027697', 88);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 55, 'Listing 99', 'Description for listing 99', 'image99.png', 293.96, false, '2024-06-20T14:49:05.434073547', 72);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 95, 'Listing 100', 'Description for listing 100', 'image100.png', 980.83, false, '2024-06-20T14:49:05.434129930', 45);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('january', 'janek2121ff@gmail.com', '$2a$10$P4RfPx5r0QGj.75OXI7vdeixu8L0lT7wvDsZ8urShTSk4V1QXizf6', 'ADMIN', true, true, true, true);
CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);
