INSERT INTO category (name, image) VALUES ('Category 1', 'category1.png');
INSERT INTO category (name, image) VALUES ('Category 2', 'category2.png');
INSERT INTO category (name, image) VALUES ('Category 3', 'category3.png');
INSERT INTO category (name, image) VALUES ('Category 4', 'category4.png');
INSERT INTO category (name, image) VALUES ('Category 5', 'category5.png');
INSERT INTO category (name, image) VALUES ('Category 6', 'category6.png');
INSERT INTO category (name, image) VALUES ('Category 7', 'category7.png');
INSERT INTO category (name, image) VALUES ('Category 8', 'category8.png');
INSERT INTO category (name, image) VALUES ('Category 9', 'category9.png');
INSERT INTO category (name, image) VALUES ('Category 10', 'category10.png');
INSERT INTO category (name, image) VALUES ('Category 11', 'category11.png');
INSERT INTO category (name, image) VALUES ('Category 12', 'category12.png');
INSERT INTO category (name, image) VALUES ('Category 13', 'category13.png');
INSERT INTO category (name, image) VALUES ('Category 14', 'category14.png');
INSERT INTO category (name, image) VALUES ('Category 15', 'category15.png');
INSERT INTO category (name, image) VALUES ('Category 16', 'category16.png');
INSERT INTO category (name, image) VALUES ('Category 17', 'category17.png');
INSERT INTO category (name, image) VALUES ('Category 18', 'category18.png');
INSERT INTO category (name, image) VALUES ('Category 19', 'category19.png');
INSERT INTO category (name, image) VALUES ('Category 20', 'category20.png');
INSERT INTO category (name, image) VALUES ('Category 21', 'category21.png');
INSERT INTO category (name, image) VALUES ('Category 22', 'category22.png');
INSERT INTO category (name, image) VALUES ('Category 23', 'category23.png');
INSERT INTO category (name, image) VALUES ('Category 24', 'category24.png');
INSERT INTO category (name, image) VALUES ('Category 25', 'category25.png');
INSERT INTO category (name, image) VALUES ('Category 26', 'category26.png');
INSERT INTO category (name, image) VALUES ('Category 27', 'category27.png');
INSERT INTO category (name, image) VALUES ('Category 28', 'category28.png');
INSERT INTO category (name, image) VALUES ('Category 29', 'category29.png');
INSERT INTO category (name, image) VALUES ('Category 30', 'category30.png');
INSERT INTO category (name, image) VALUES ('Category 31', 'category31.png');
INSERT INTO category (name, image) VALUES ('Category 32', 'category32.png');
INSERT INTO category (name, image) VALUES ('Category 33', 'category33.png');
INSERT INTO category (name, image) VALUES ('Category 34', 'category34.png');
INSERT INTO category (name, image) VALUES ('Category 35', 'category35.png');
INSERT INTO category (name, image) VALUES ('Category 36', 'category36.png');
INSERT INTO category (name, image) VALUES ('Category 37', 'category37.png');
INSERT INTO category (name, image) VALUES ('Category 38', 'category38.png');
INSERT INTO category (name, image) VALUES ('Category 39', 'category39.png');
INSERT INTO category (name, image) VALUES ('Category 40', 'category40.png');
INSERT INTO category (name, image) VALUES ('Category 41', 'category41.png');
INSERT INTO category (name, image) VALUES ('Category 42', 'category42.png');
INSERT INTO category (name, image) VALUES ('Category 43', 'category43.png');
INSERT INTO category (name, image) VALUES ('Category 44', 'category44.png');
INSERT INTO category (name, image) VALUES ('Category 45', 'category45.png');
INSERT INTO category (name, image) VALUES ('Category 46', 'category46.png');
INSERT INTO category (name, image) VALUES ('Category 47', 'category47.png');
INSERT INTO category (name, image) VALUES ('Category 48', 'category48.png');
INSERT INTO category (name, image) VALUES ('Category 49', 'category49.png');
INSERT INTO category (name, image) VALUES ('Category 50', 'category50.png');
INSERT INTO category (name, image) VALUES ('Category 51', 'category51.png');
INSERT INTO category (name, image) VALUES ('Category 52', 'category52.png');
INSERT INTO category (name, image) VALUES ('Category 53', 'category53.png');
INSERT INTO category (name, image) VALUES ('Category 54', 'category54.png');
INSERT INTO category (name, image) VALUES ('Category 55', 'category55.png');
INSERT INTO category (name, image) VALUES ('Category 56', 'category56.png');
INSERT INTO category (name, image) VALUES ('Category 57', 'category57.png');
INSERT INTO category (name, image) VALUES ('Category 58', 'category58.png');
INSERT INTO category (name, image) VALUES ('Category 59', 'category59.png');
INSERT INTO category (name, image) VALUES ('Category 60', 'category60.png');
INSERT INTO category (name, image) VALUES ('Category 61', 'category61.png');
INSERT INTO category (name, image) VALUES ('Category 62', 'category62.png');
INSERT INTO category (name, image) VALUES ('Category 63', 'category63.png');
INSERT INTO category (name, image) VALUES ('Category 64', 'category64.png');
INSERT INTO category (name, image) VALUES ('Category 65', 'category65.png');
INSERT INTO category (name, image) VALUES ('Category 66', 'category66.png');
INSERT INTO category (name, image) VALUES ('Category 67', 'category67.png');
INSERT INTO category (name, image) VALUES ('Category 68', 'category68.png');
INSERT INTO category (name, image) VALUES ('Category 69', 'category69.png');
INSERT INTO category (name, image) VALUES ('Category 70', 'category70.png');
INSERT INTO category (name, image) VALUES ('Category 71', 'category71.png');
INSERT INTO category (name, image) VALUES ('Category 72', 'category72.png');
INSERT INTO category (name, image) VALUES ('Category 73', 'category73.png');
INSERT INTO category (name, image) VALUES ('Category 74', 'category74.png');
INSERT INTO category (name, image) VALUES ('Category 75', 'category75.png');
INSERT INTO category (name, image) VALUES ('Category 76', 'category76.png');
INSERT INTO category (name, image) VALUES ('Category 77', 'category77.png');
INSERT INTO category (name, image) VALUES ('Category 78', 'category78.png');
INSERT INTO category (name, image) VALUES ('Category 79', 'category79.png');
INSERT INTO category (name, image) VALUES ('Category 80', 'category80.png');
INSERT INTO category (name, image) VALUES ('Category 81', 'category81.png');
INSERT INTO category (name, image) VALUES ('Category 82', 'category82.png');
INSERT INTO category (name, image) VALUES ('Category 83', 'category83.png');
INSERT INTO category (name, image) VALUES ('Category 84', 'category84.png');
INSERT INTO category (name, image) VALUES ('Category 85', 'category85.png');
INSERT INTO category (name, image) VALUES ('Category 86', 'category86.png');
INSERT INTO category (name, image) VALUES ('Category 87', 'category87.png');
INSERT INTO category (name, image) VALUES ('Category 88', 'category88.png');
INSERT INTO category (name, image) VALUES ('Category 89', 'category89.png');
INSERT INTO category (name, image) VALUES ('Category 90', 'category90.png');
INSERT INTO category (name, image) VALUES ('Category 91', 'category91.png');
INSERT INTO category (name, image) VALUES ('Category 92', 'category92.png');
INSERT INTO category (name, image) VALUES ('Category 93', 'category93.png');
INSERT INTO category (name, image) VALUES ('Category 94', 'category94.png');
INSERT INTO category (name, image) VALUES ('Category 95', 'category95.png');
INSERT INTO category (name, image) VALUES ('Category 96', 'category96.png');
INSERT INTO category (name, image) VALUES ('Category 97', 'category97.png');
INSERT INTO category (name, image) VALUES ('Category 98', 'category98.png');
INSERT INTO category (name, image) VALUES ('Category 99', 'category99.png');
INSERT INTO category (name, image) VALUES ('Category 100', 'category100.png');
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user1', 'user1@gmail.com', '$2a$10$5ytsqIy9qd3i7MYyWK6yx.9sr84qVRL8cg9TIB/LSIrzeUl.Q61XW', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user2', 'user2@gmail.com', '$2a$10$zwIlD1c4uB8BqSO0I.5qQ.UNaUdCxdPrYNkyC8QhLKR8SdhPxq7xm', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user3', 'user3@gmail.com', '$2a$10$.3EFXYikqLvnkbPdreIKVu6Bon2isnNeD2JB16oFy0yXYQBaLMJFa', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user4', 'user4@gmail.com', '$2a$10$d99nolaufd4BG8iglP7H4e97k2mqgDv5vWcH/AOVzEZ9hoKzf1rVe', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user5', 'user5@gmail.com', '$2a$10$drwXk12D6Hmfvs9jo52/C.52372ucEnKrazz/qeHaTI4cP.U2LJwC', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user6', 'user6@gmail.com', '$2a$10$dz7I7LfiNkLDZRXsu.260OCeVilHaX3jXKckMsQ4V8lx2NPkczG/m', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user7', 'user7@gmail.com', '$2a$10$hRwLzcOnHC7opQkBeo58.uSiP7uuYLb5vORVng7vvhoJv3wi.zb.K', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user8', 'user8@gmail.com', '$2a$10$kHpkCAcQFXIu8bKKj3OH0ufk4lC3ssaqVww7DfU.tpK.w/f5nHhum', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user9', 'user9@gmail.com', '$2a$10$fp974X4fO0gGTGr1y7j5POfIOvVNmRqQ6FfOpWcPO6d56AuSj0XpO', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user10', 'user10@gmail.com', '$2a$10$cIpDC.JRFvMXS3GL6K9ft.cfayXNFkCulUehNdwFvEAnsiBp91Z4a', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user11', 'user11@gmail.com', '$2a$10$uzGdUluCUFe7IuKWLxcX8OmCyspsmJY1yLxToqdenNSVDICuVlnUK', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user12', 'user12@gmail.com', '$2a$10$7aYCHxmNWCUANKVCs9a0M.z1D.ZtHNJ0TH.KQcT2A4Z/Eg6HGznRa', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user13', 'user13@gmail.com', '$2a$10$fwh8rbbruv8E/fMKX36ywOkJiVwL6hiGgPp7Rspk6MlKsnwNrC3ZW', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user14', 'user14@gmail.com', '$2a$10$5kYohIvfxcvs2sVHzSpfc.BJFQx9zZPIhSDMsgpA7QRY6SrFyiOVS', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user15', 'user15@gmail.com', '$2a$10$IXCuWtJd08s/2142jA7gKOb4K2NqtuAioqMrrV0.zVAF17dm7PLTW', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user16', 'user16@gmail.com', '$2a$10$Ewh0v17L2NZzcWMcQ/lVn.5tOGW1M66RZ.u97chsRM6AM7snLvCjm', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user17', 'user17@gmail.com', '$2a$10$0ChY496cJuVMo5Uy5Du7F.6B56EriUNtOhbskiF9N1bid0vPynImy', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user18', 'user18@gmail.com', '$2a$10$KiMXez61ll3JYocr357AKOLNZHfWgG9VWVyPMoeS8FJwqLJazehqa', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user19', 'user19@gmail.com', '$2a$10$ib5UlozOXt00JSyB1hJes.LNvgEajeHQw4mNE2FCOTWCQxTOGLR8G', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user20', 'user20@gmail.com', '$2a$10$liUtJkFit86XqmcTng.aYu.5v10zzUfTn8j6pJdVGrLW/A25.lv6y', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user21', 'user21@gmail.com', '$2a$10$SUCZjVCRskj76GkXiNDvAuvorPiwaK.QTPk3bitut.needCp5zWVy', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user22', 'user22@gmail.com', '$2a$10$pJGSmQIKFT92bGEB4PV/QOBxQNZ8nHtvukHMLYsQfMpyFZdfVNGNK', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user23', 'user23@gmail.com', '$2a$10$IhfxyDBIbEWhakENQRae/eahcQH8T07W/i.h5x38HOU.tr8vee2OK', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user24', 'user24@gmail.com', '$2a$10$6SmBIeNduaqloA1i4Ygoh.xknWhfNFTcSrxeu0hg4hT6I3t196zty', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user25', 'user25@gmail.com', '$2a$10$2oZLahjO0rJ7bolksPucCeMPeE5Oan56p9KzDnz/UkG.MVAkueZlW', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user26', 'user26@gmail.com', '$2a$10$DKMacPyZWofqUFA/Pj/qbO9fFVHckODVExenj.W27q.ganPhnaUyK', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user27', 'user27@gmail.com', '$2a$10$lZuTC5d0.h.HDM/vYM5tB./WQR00bcuOhwA540PnJv2t6Wg.KLb6e', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user28', 'user28@gmail.com', '$2a$10$d7xzQbNM4IzJOljd60x9NOWbdJAoi1Nrwxt0QXhbUyb.X2HWimOrO', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user29', 'user29@gmail.com', '$2a$10$dsPU3v3Ovax1lL9jpmvHm.LiUYJEsLFF3ZkgsH/2/0rNDycQ1Cc/m', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user30', 'user30@gmail.com', '$2a$10$7/1C/OGVH.ElqEOxO3NCAO23AHfGqmzZu3L6qTiPO73ZdufflnjIq', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user31', 'user31@gmail.com', '$2a$10$mh6Z8XNaBb5I9zKtVSdNIuBgxskvFejQVGV11rh/If.PkSf6SgAWK', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user32', 'user32@gmail.com', '$2a$10$nglWoheXG1Yqw6UH0hHDwe8ig/NgupTPzHXIeLIJtUJqvXDlC9Rwu', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user33', 'user33@gmail.com', '$2a$10$38GS/l9KuMHtYtlE6i.cauBCH4jaEeRL9nikpW/6fDB.0vUn6x7WC', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user34', 'user34@gmail.com', '$2a$10$w.XFxnOBc1Am4zWoCt103uFpQtqI9FK0OPyBLcd56ToaICM7nXdVO', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user35', 'user35@gmail.com', '$2a$10$o2hY/J1wDmJOQ.gqUpy6m.JWO4LqPwpP/2Tk/nTYI/K1WtNytgay2', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user36', 'user36@gmail.com', '$2a$10$utTyP2ptWuFKb/zqn8XR8uryvATu4y0ro/6frg7mszS6zAhSdX6/a', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user37', 'user37@gmail.com', '$2a$10$I4Bi2WmCeFlchMWqxdHtROEL6ZHKnT/vuQ/S9UTIH6csO3uZ.JPd2', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user38', 'user38@gmail.com', '$2a$10$xwKUSCRvDGTgWCW8rlR.jeD.sReJgrTdzk/ryBYIUZw/KLBk3mwmq', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user39', 'user39@gmail.com', '$2a$10$CCcGwz2/ZA/C11M58UrHqOdSSR4BiCOFd5.Lc1RVEam1wOy6cdXX.', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user40', 'user40@gmail.com', '$2a$10$jSFS92XIT0MyROtWhIVVMeVAXlpITyGuWjqZ5hoLqt8wc8C1PIUQG', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user41', 'user41@gmail.com', '$2a$10$WoW3BW8q/b29ZJ2BENQNpOsoeg.Mh5yUzzpCuAnSp/jX6RYadkP66', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user42', 'user42@gmail.com', '$2a$10$T9imzf4uOApXULDx0SaBr.HGL3kHh2e.wTgjaWLmEItYRrkOYW8jS', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user43', 'user43@gmail.com', '$2a$10$gFteDVK0QGNL8JlX2yX5Cu9re6FzQur0pAU0LS2IlAbqSwek5H0Pm', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user44', 'user44@gmail.com', '$2a$10$WgoiTDgocjytMhbZ2boGqOefjaJwgSQ/s4Acee1SflRI0cBTS2CEe', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user45', 'user45@gmail.com', '$2a$10$PL6NSj7/HQdIBQG43laHa.ERUzHTmv3L.hcUyKZyEIEcDPN9u5E5y', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user46', 'user46@gmail.com', '$2a$10$m./XHEI/jVjHOVvFULd7EO3WM3vydidJQTqU2.L8DEDuzbkxPGc5K', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user47', 'user47@gmail.com', '$2a$10$tFf4CJWKEDN9SXD/qJZhJ.gsEK7SnfXOaEeu3HrE1w8L1o3jBEEna', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user48', 'user48@gmail.com', '$2a$10$fovV5nOto1hXdqxJ6kLMNOvF6ZkUdqhHnj.6ol4l8ZUzdukFWZeTi', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user49', 'user49@gmail.com', '$2a$10$NNt1L6FjOUGZCY8fDoyhL.xAUxZzpDLc7cHEKC0RC1KNfPtx0bgve', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user50', 'user50@gmail.com', '$2a$10$RtMWryL9.BE/wevS6zR92uvfuRAtrneJbr0h4S6bTaw/xhidAqBim', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user51', 'user51@gmail.com', '$2a$10$EBlqdomGbm8Sr9WDrJOpC.W9sVQj6q5Ct21Wp6cflyGGsntwvEa1i', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user52', 'user52@gmail.com', '$2a$10$ZtGgrk8EPVYVBlSKUImlGO85RomuKscLKRTTVRtvZt6Lktw3Q5BQ2', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user53', 'user53@gmail.com', '$2a$10$2pRy1bVijycBdvUGD8cdHON83vB820GTlcTl0DhVic1T/dKD6xGhm', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user54', 'user54@gmail.com', '$2a$10$iVy3McBMdmDFjVT4CUaTSuIIqVaUXRZmN/tb1m9s6QN/LrHRCBZVS', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user55', 'user55@gmail.com', '$2a$10$Dox0o1KlP2G98oo2M8zJwe70p4aOmgAkdXdSfLtt7xDq9ottP4vuu', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user56', 'user56@gmail.com', '$2a$10$wYMe0bMDWiIg436eHbxu..6rCXxSdJ3CeLP.0/zXLfu2w5Cgi.3HS', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user57', 'user57@gmail.com', '$2a$10$V9Tp3/QHRDKdbWQCGQhgIekW2utHQ/X3uYolei7RMUchtlH.tlfeK', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user58', 'user58@gmail.com', '$2a$10$FMrKNhF1y.IDoZYJRRLR1O4ZphqOvbvXMRqc26ecriI4rRw9TJ/U.', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user59', 'user59@gmail.com', '$2a$10$u.LnSYNemZ8d9IIWC8Xb3OKlIecJEgMOs2pjBUrfPRA1fd.wUCJW6', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user60', 'user60@gmail.com', '$2a$10$W2qjAPWXcLjNdml2TOysU.EgleB59NH9lC2cjCKxymne826n81J.u', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user61', 'user61@gmail.com', '$2a$10$STOh3s5LJiR2uL6H4I71sOvKzit2LiKcaPbjs8OaAKtiXmtvgx5Qa', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user62', 'user62@gmail.com', '$2a$10$BKT11HVnfFf/2a/wbdy2Hee1LSsD.p482ziL5Kl4FugZ0iCCOa.De', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user63', 'user63@gmail.com', '$2a$10$CDxESZq2/YhxJFuW16iVSOLLEBoCzy0lznzGdL07ukv0hEqYVPQr6', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user64', 'user64@gmail.com', '$2a$10$HaD1fSoG31YqZ1nXoSc4suf4wkOl5uUQqYAvUq2KQTuQiRDrGtSo6', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user65', 'user65@gmail.com', '$2a$10$YKsgPcTUU5snhl50W5cemOU5M0g8TtBJqZNNLftpPAET/1/fNYYlW', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user66', 'user66@gmail.com', '$2a$10$kH5WEP3yiFov4izxLOUy9OKDOnc09395.3qJCa1G1knDoyM3awzpS', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user67', 'user67@gmail.com', '$2a$10$48y1vgl0aCfHmiMTA/8QSuZFalpPwmTpZZPiHbNnmIC1b.wA2eqLC', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user68', 'user68@gmail.com', '$2a$10$tKfX7i/qJg8JTrH/3WysrOislv5Dao8aDCZ3In2e0MDV6qqdsCcqS', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user69', 'user69@gmail.com', '$2a$10$4KZFtDV6L3malQBFNxIu3.o.Ik.jO68VVdn4eajNoyOYqmrdkLquG', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user70', 'user70@gmail.com', '$2a$10$LW0YjJ/WymjLXZbAYjEsduztHHHWoB1LKfRFph9JcKpKn8QErys7u', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user71', 'user71@gmail.com', '$2a$10$ddByPwFkb6e5WOdOSFdbQeZMR.x89vlXeau7NijjcBr77q4V29YFa', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user72', 'user72@gmail.com', '$2a$10$x5CSJanOXJgTHwU4tvIlsOVsDjoGv5xIDdv8m/RU39kpmm5K.I4RO', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user73', 'user73@gmail.com', '$2a$10$omtHq5yU/KGpGooC6AIeeeKkEjGqFDK.kYBPFkerasi0TgXYzHjKW', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user74', 'user74@gmail.com', '$2a$10$G3YpXin6mEUCXgKAREA9IOUrVMz2d1htgpR2TjlL.CqEfdvkVUYpS', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user75', 'user75@gmail.com', '$2a$10$6c03MPTuIIYb9jf7S.syJ.rPIj/r7l3lU1FWZd/ABQgHyuuwIcVdS', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user76', 'user76@gmail.com', '$2a$10$pNCKIHiLx0F2/x2vk/asguROsvIVm1Jnb6nWCgfKWZ9fAHgP2a78m', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user77', 'user77@gmail.com', '$2a$10$UdiLvLbczRLsZ.jRV7A8/OJwuNjGjiEh8pJhsN1GTmBJexyJWgPai', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user78', 'user78@gmail.com', '$2a$10$UoGcqSOXJiXqGe18jOIxqejCJDypVM0TcJOc46d4jXzxUWx1A3shG', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user79', 'user79@gmail.com', '$2a$10$/Uij8kWlEUIfbIlIVrTWNOCWZBtypyi2UdLynX0L4KDB40dGQ0gsS', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user80', 'user80@gmail.com', '$2a$10$HjFTEos6J4/Fv.QJeTqa2OtPpjGTZV2XeUJMxO9x9D7CntbpCIvvq', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user81', 'user81@gmail.com', '$2a$10$Ex9EoZLcl/YIWJHu/paAk.uzPAOIbdrplAZ5NQqUr9Yoki05j.p0e', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user82', 'user82@gmail.com', '$2a$10$.xsh7z1w1AFyvvtwHuitJexYgH0V3ZqQuyYvLBVFiLZGH.xxpb4mO', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user83', 'user83@gmail.com', '$2a$10$uHFJWUq1liTjcG8Nx6pXyeex3vNt0hSylJ5KFg/Yh34r14NBnENYu', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user84', 'user84@gmail.com', '$2a$10$N7UUNQUPKYzdHIXi.PC9WO2x5vyOefQxZaecKqvqszqL8Zdf5VmM2', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user85', 'user85@gmail.com', '$2a$10$xygwW2fXg.Y2MMZsK2zJa.eU8j3vJ2T0mSJGLaByJMY.nerV7gueu', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user86', 'user86@gmail.com', '$2a$10$PW9xV/SDMLCmCmELHZlAOej4mKNe4XliMSS97h4Ewxvpu3sLcDVDC', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user87', 'user87@gmail.com', '$2a$10$tILtvEAz0.WkRIU3aJmjFuGjqF5HfuwUdji5B/gF0sjl2yIOtIK0W', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user88', 'user88@gmail.com', '$2a$10$Jf.nMP0Ivtiew0NAZP/6EeaLZzNZHuujcEX8KJY9x05WbXzxYjOUW', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user89', 'user89@gmail.com', '$2a$10$z4OfhhfUYqWmUXVdVAx8lumlqys2uuu4nCdWnv8MxuzpWq8bh/2oO', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user90', 'user90@gmail.com', '$2a$10$C0vEaGxY01.Q6xOCFQpe1.vffitZuAEFnTf1f/KM7J06a/xw/PUBS', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user91', 'user91@gmail.com', '$2a$10$ceeCwV8SzdRZ7MOzwcsgt.dzESL0KUcRtKaMvTIkJQm4wR5M3stoO', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user92', 'user92@gmail.com', '$2a$10$75tvlWk3QdtUbMon5x7GoeC3abgIYJoquDgplKqoTMz5UBezXOB/G', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user93', 'user93@gmail.com', '$2a$10$Y9b0Wssdwxydd8/KuMesLu6P./B48Hf65xCcrR0q2B.PnXgjBMMP6', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user94', 'user94@gmail.com', '$2a$10$mL7DtkaZgKwo5SCFrW1XIezbPYF/PRPrJf7c8vIi96EvxCKi7quH.', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user95', 'user95@gmail.com', '$2a$10$UZq8SJRB2PNXQkLBZeUltOITk7z5CDfZLf7t5pKaRIHmcRj/6D212', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user96', 'user96@gmail.com', '$2a$10$txC0M7GxPawfgouanybLme.txG6IS9KPa0zLkvz40rBjAqI0/Eyz.', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user97', 'user97@gmail.com', '$2a$10$R9iHfEZQSM4dlxQKWZ2XpOP6AcxVHndazFdn0sPkNV1FtvjPYC.xK', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user98', 'user98@gmail.com', '$2a$10$9W.6EsEIGBvbNt9p2E3JpurIknuFPNx/td7yIe9PUiuhKy2j7BrWC', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user99', 'user99@gmail.com', '$2a$10$5OSmTeJP8s7aG59sUdKGyuD/VYXvmorVKKoSBTm.lGGXWxQ0SGnBm', 'USER', true, true, true, true);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('user100', 'user100@gmail.com', '$2a$10$0lN/AJDuxPtElADus7MrGue4HQixW.SgBJIKVivoMLpQH2gdha9pC', 'USER', true, true, true, true);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 86, 'Listing 1', 'Description for listing 1', 'image1.png', 808.88, false, '2024-06-18T13:28:17.105610108', 55);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 46, 'Listing 2', 'Description for listing 2', 'image2.png', 551.74, false, '2024-06-18T13:28:17.107269457', 18);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 93, 'Listing 3', 'Description for listing 3', 'image3.png', 991.37, false, '2024-06-18T13:28:17.107383498', 15);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 89, 'Listing 4', 'Description for listing 4', 'image4.png', 211.06, false, '2024-06-18T13:28:17.107485316', 15);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 55, 'Listing 5', 'Description for listing 5', 'image5.png', 528.35, false, '2024-06-18T13:28:17.107563108', 26);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 70, 'Listing 6', 'Description for listing 6', 'image6.png', 772.39, false, '2024-06-18T13:28:17.107637142', 5);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 18, 'Listing 7', 'Description for listing 7', 'image7.png', 82.65, false, '2024-06-18T13:28:17.107726784', 43);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 69, 'Listing 8', 'Description for listing 8', 'image8.png', 354.68, false, '2024-06-18T13:28:17.107803788', 21);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 63, 'Listing 9', 'Description for listing 9', 'image9.png', 286.61, false, '2024-06-18T13:28:17.107884793', 80);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 74, 'Listing 10', 'Description for listing 10', 'image10.png', 981.26, false, '2024-06-18T13:28:17.107982168', 5);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 54, 'Listing 11', 'Description for listing 11', 'image11.png', 116.79, false, '2024-06-18T13:28:17.108062436', 27);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 75, 'Listing 12', 'Description for listing 12', 'image12.png', 589.32, false, '2024-06-18T13:28:17.108214094', 97);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 13, 'Listing 13', 'Description for listing 13', 'image13.png', 167.19, false, '2024-06-18T13:28:17.108288558', 82);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 48, 'Listing 14', 'Description for listing 14', 'image14.png', 385.60, false, '2024-06-18T13:28:17.108372009', 19);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 4, 'Listing 15', 'Description for listing 15', 'image15.png', 597.90, false, '2024-06-18T13:28:17.108454465', 100);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 36, 'Listing 16', 'Description for listing 16', 'image16.png', 622.87, false, '2024-06-18T13:28:17.108529429', 76);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 31, 'Listing 17', 'Description for listing 17', 'image17.png', 763.44, false, '2024-06-18T13:28:17.108601550', 96);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 6, 'Listing 18', 'Description for listing 18', 'image18.png', 489.38, false, '2024-06-18T13:28:17.108684443', 3);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 42, 'Listing 19', 'Description for listing 19', 'image19.png', 784.25, false, '2024-06-18T13:28:17.108758307', 27);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 69, 'Listing 20', 'Description for listing 20', 'image20.png', 953.16, false, '2024-06-18T13:28:17.108837893', 22);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 100, 'Listing 21', 'Description for listing 21', 'image21.png', 614.35, false, '2024-06-18T13:28:17.108914580', 99);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 55, 'Listing 22', 'Description for listing 22', 'image22.png', 83.79, false, '2024-06-18T13:28:17.108991715', 70);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 32, 'Listing 23', 'Description for listing 23', 'image23.png', 479.85, false, '2024-06-18T13:28:17.109075780', 77);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 2, 'Listing 24', 'Description for listing 24', 'image24.png', 585.81, false, '2024-06-18T13:28:17.109238830', 25);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 66, 'Listing 25', 'Description for listing 25', 'image25.png', 915.34, false, '2024-06-18T13:28:17.109317912', 100);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 69, 'Listing 26', 'Description for listing 26', 'image26.png', 21.54, false, '2024-06-18T13:28:17.109397636', 43);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 74, 'Listing 27', 'Description for listing 27', 'image27.png', 9.10, false, '2024-06-18T13:28:17.109482902', 72);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 27, 'Listing 28', 'Description for listing 28', 'image28.png', 475.24, false, '2024-06-18T13:28:17.109581826', 39);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 3, 'Listing 29', 'Description for listing 29', 'image29.png', 882.89, false, '2024-06-18T13:28:17.109693852', 63);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 95, 'Listing 30', 'Description for listing 30', 'image30.png', 216.21, false, '2024-06-18T13:28:17.109799442', 68);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 57, 'Listing 31', 'Description for listing 31', 'image31.png', 878.66, false, '2024-06-18T13:28:17.109907532', 52);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 74, 'Listing 32', 'Description for listing 32', 'image32.png', 255.39, false, '2024-06-18T13:28:17.110030529', 91);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 47, 'Listing 33', 'Description for listing 33', 'image33.png', 401.92, false, '2024-06-18T13:28:17.110225380', 64);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 99, 'Listing 34', 'Description for listing 34', 'image34.png', 558.29, false, '2024-06-18T13:28:17.110344711', 93);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 61, 'Listing 35', 'Description for listing 35', 'image35.png', 880.15, false, '2024-06-18T13:28:17.110453199', 78);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 62, 'Listing 36', 'Description for listing 36', 'image36.png', 76.30, false, '2024-06-18T13:28:17.110575600', 15);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 23, 'Listing 37', 'Description for listing 37', 'image37.png', 834.96, false, '2024-06-18T13:28:17.110675880', 40);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 7, 'Listing 38', 'Description for listing 38', 'image38.png', 689.14, false, '2024-06-18T13:28:17.110780', 19);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 91, 'Listing 39', 'Description for listing 39', 'image39.png', 637.83, false, '2024-06-18T13:28:17.110886790', 22);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 76, 'Listing 40', 'Description for listing 40', 'image40.png', 613.31, false, '2024-06-18T13:28:17.110988305', 86);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 75, 'Listing 41', 'Description for listing 41', 'image41.png', 121.76, false, '2024-06-18T13:28:17.111088085', 32);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 8, 'Listing 42', 'Description for listing 42', 'image42.png', 824.29, false, '2024-06-18T13:28:17.111278694', 70);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 52, 'Listing 43', 'Description for listing 43', 'image43.png', 855.06, false, '2024-06-18T13:28:17.111393983', 5);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 4, 'Listing 44', 'Description for listing 44', 'image44.png', 564.88, false, '2024-06-18T13:28:17.111500450', 91);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 43, 'Listing 45', 'Description for listing 45', 'image45.png', 548.53, false, '2024-06-18T13:28:17.111612115', 20);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 9, 'Listing 46', 'Description for listing 46', 'image46.png', 67.57, false, '2024-06-18T13:28:17.111722844', 3);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 3, 'Listing 47', 'Description for listing 47', 'image47.png', 763.44, false, '2024-06-18T13:28:17.111844472', 95);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 68, 'Listing 48', 'Description for listing 48', 'image48.png', 205.84, false, '2024-06-18T13:28:17.111939439', 83);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 9, 'Listing 49', 'Description for listing 49', 'image49.png', 815.50, false, '2024-06-18T13:28:17.112040481', 7);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 44, 'Listing 50', 'Description for listing 50', 'image50.png', 907.44, false, '2024-06-18T13:28:17.112202550', 45);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 2, 'Listing 51', 'Description for listing 51', 'image51.png', 528.53, false, '2024-06-18T13:28:17.112310785', 85);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 63, 'Listing 52', 'Description for listing 52', 'image52.png', 812.13, false, '2024-06-18T13:28:17.112423292', 85);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 84, 'Listing 53', 'Description for listing 53', 'image53.png', 281.80, false, '2024-06-18T13:28:17.112533326', 65);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 24, 'Listing 54', 'Description for listing 54', 'image54.png', 836.88, false, '2024-06-18T13:28:17.112793885', 95);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 41, 'Listing 55', 'Description for listing 55', 'image55.png', 616.14, false, '2024-06-18T13:28:17.112901698', 11);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 41, 'Listing 56', 'Description for listing 56', 'image56.png', 23.71, false, '2024-06-18T13:28:17.113004289', 73);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 18, 'Listing 57', 'Description for listing 57', 'image57.png', 516.57, false, '2024-06-18T13:28:17.113149655', 23);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 47, 'Listing 58', 'Description for listing 58', 'image58.png', 288.27, false, '2024-06-18T13:28:17.113280792', 30);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 8, 'Listing 59', 'Description for listing 59', 'image59.png', 372.97, false, '2024-06-18T13:28:17.113425019', 6);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 85, 'Listing 60', 'Description for listing 60', 'image60.png', 461.82, false, '2024-06-18T13:28:17.113534680', 96);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 70, 'Listing 61', 'Description for listing 61', 'image61.png', 535.19, false, '2024-06-18T13:28:17.113637371', 60);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 33, 'Listing 62', 'Description for listing 62', 'image62.png', 324.77, false, '2024-06-18T13:28:17.113758659', 83);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 4, 'Listing 63', 'Description for listing 63', 'image63.png', 325.65, false, '2024-06-18T13:28:17.113851961', 93);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 13, 'Listing 64', 'Description for listing 64', 'image64.png', 167.19, false, '2024-06-18T13:28:17.113964666', 88);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 49, 'Listing 65', 'Description for listing 65', 'image65.png', 349.53, false, '2024-06-18T13:28:17.114066178', 23);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 1, 'Listing 66', 'Description for listing 66', 'image66.png', 779.38, false, '2024-06-18T13:28:17.114170788', 50);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 74, 'Listing 67', 'Description for listing 67', 'image67.png', 951.94, false, '2024-06-18T13:28:17.114278875', 44);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 75, 'Listing 68', 'Description for listing 68', 'image68.png', 675.47, false, '2024-06-18T13:28:17.114408070', 69);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 96, 'Listing 69', 'Description for listing 69', 'image69.png', 711.10, false, '2024-06-18T13:28:17.114507625', 85);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 62, 'Listing 70', 'Description for listing 70', 'image70.png', 783.34, false, '2024-06-18T13:28:17.114600799', 96);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 1, 'Listing 71', 'Description for listing 71', 'image71.png', 928.08, false, '2024-06-18T13:28:17.114705746', 63);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 55, 'Listing 72', 'Description for listing 72', 'image72.png', 796.33, false, '2024-06-18T13:28:17.114797231', 17);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 26, 'Listing 73', 'Description for listing 73', 'image73.png', 176.11, false, '2024-06-18T13:28:17.114883688', 34);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 86, 'Listing 74', 'Description for listing 74', 'image74.png', 875.09, false, '2024-06-18T13:28:17.114971934', 97);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 7, 'Listing 75', 'Description for listing 75', 'image75.png', 106.23, false, '2024-06-18T13:28:17.115068479', 94);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 58, 'Listing 76', 'Description for listing 76', 'image76.png', 412.67, false, '2024-06-18T13:28:17.115166914', 95);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 14, 'Listing 77', 'Description for listing 77', 'image77.png', 871.20, false, '2024-06-18T13:28:17.115261992', 68);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 16, 'Listing 78', 'Description for listing 78', 'image78.png', 131.28, false, '2024-06-18T13:28:17.115365927', 5);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 83, 'Listing 79', 'Description for listing 79', 'image79.png', 725.77, false, '2024-06-18T13:28:17.115461327', 60);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 67, 'Listing 80', 'Description for listing 80', 'image80.png', 866.31, false, '2024-06-18T13:28:17.115551224', 40);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 95, 'Listing 81', 'Description for listing 81', 'image81.png', 588.89, false, '2024-06-18T13:28:17.115659855', 70);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 54, 'Listing 82', 'Description for listing 82', 'image82.png', 11.24, false, '2024-06-18T13:28:17.115765149', 34);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 59, 'Listing 83', 'Description for listing 83', 'image83.png', 612.55, false, '2024-06-18T13:28:17.115853169', 66);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 88, 'Listing 84', 'Description for listing 84', 'image84.png', 746.54, false, '2024-06-18T13:28:17.115939767', 11);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 93, 'Listing 85', 'Description for listing 85', 'image85.png', 91.51, false, '2024-06-18T13:28:17.116035655', 81);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 75, 'Listing 86', 'Description for listing 86', 'image86.png', 856.26, false, '2024-06-18T13:28:17.116139800', 54);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 19, 'Listing 87', 'Description for listing 87', 'image87.png', 369.85, false, '2024-06-18T13:28:17.116328005', 83);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 25, 'Listing 88', 'Description for listing 88', 'image88.png', 148.02, false, '2024-06-18T13:28:17.116426923', 95);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 6, 'Listing 89', 'Description for listing 89', 'image89.png', 752.66, false, '2024-06-18T13:28:17.116533761', 93);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 42, 'Listing 90', 'Description for listing 90', 'image90.png', 235.15, false, '2024-06-18T13:28:17.116635881', 13);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 83, 'Listing 91', 'Description for listing 91', 'image91.png', 814.96, false, '2024-06-18T13:28:17.116720642', 54);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 35, 'Listing 92', 'Description for listing 92', 'image92.png', 714.33, false, '2024-06-18T13:28:17.116814051', 75);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 33, 'Listing 93', 'Description for listing 93', 'image93.png', 915.00, false, '2024-06-18T13:28:17.116922701', 52);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 83, 'Listing 94', 'Description for listing 94', 'image94.png', 577.46, false, '2024-06-18T13:28:17.117004830', 64);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 64, 'Listing 95', 'Description for listing 95', 'image95.png', 165.45, false, '2024-06-18T13:28:17.117088891', 93);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 97, 'Listing 96', 'Description for listing 96', 'image96.png', 33.71, false, '2024-06-18T13:28:17.117194787', 33);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 43, 'Listing 97', 'Description for listing 97', 'image97.png', 593.37, false, '2024-06-18T13:28:17.117285889', 20);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 32, 'Listing 98', 'Description for listing 98', 'image98.png', 785.72, false, '2024-06-18T13:28:17.117371024', 99);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 75, 'Listing 99', 'Description for listing 99', 'image99.png', 728.83, false, '2024-06-18T13:28:17.117451800', 35);
INSERT INTO listing (user_id, name, description, image, price, approved, expiry_date, category_id) VALUES ( 37, 'Listing 100', 'Description for listing 100', 'image100.png', 203.21, false, '2024-06-18T13:28:17.117540075', 54);
INSERT INTO _user (username, email, password, role, enabled, account_non_expired, credentials_non_expired, account_non_locked) VALUES ('january', 'janek2121ff@gmail.com', '$2a$10$6Z3N.ay.kF8XN8kuMBOhFe4bL0AvO0gqLrAcK7ThZK2XhU5mTJ.kq', 'ADMIN', true, true, true, true);
CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);
